<a href="https://colab.research.google.com/github/gaudhami4/task1/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config())

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(x.size)
print(x.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
arr1=np.zeros(10)
arr1[4]=1
print(arr1)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
arr1=np.arange(10,50)
print(arr1)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
arr1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=np.array([1,2,0,0,4,0])
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x=np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
print(x)

[[[0.14801282 0.80662744 0.47684525]
  [0.96118282 0.69724501 0.68759746]
  [0.58566223 0.25265408 0.985905  ]]

 [[0.66616676 0.07078379 0.12217377]
  [0.11504599 0.55498266 0.14236118]
  [0.29071659 0.9644209  0.39723917]]

 [[0.34565211 0.95681911 0.00615902]
  [0.36780898 0.91419075 0.93161738]
  [0.95927222 0.24877802 0.91412309]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
xmin,xmax=x.min(),x.max()
print(xmin,xmax)

0.019806849613107858 0.9989187680208528


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x=np.random.random(10)
np.mean(x)

0.3628229003051894

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x=np.ones((3,3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
false

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x=np.diag([1,2,3,4])
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
xmax, xmin = x.max(), x.min()
x= (x-xmin)/(xmax-xmin)
print (x)

[[0.23693985 0.80587045 0.70544965 0.96295272 0.09608932]
 [0.23871363 1.         0.         0.20674837 0.28037151]
 [0.08208041 0.42608936 0.67716259 0.37418071 0.76760251]
 [0.26814954 0.43816358 0.24153775 0.74932211 0.48829156]
 [0.39988431 0.82121222 0.52945969 0.3126     0.43481956]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x= np.dot(np.ones((5,3)), np.ones((3,2)))
print (x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x=np.arange(10)
x[(x>=3) &(x<=8)]=-1

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)),x))
print(np.where(x>0,np.ceil(x),np.floor(x)))

[ 1.  6.  3. -3. -3. -1.  8. -6. -1. -4.]
[ 1.  6.  3. -3. -3. -1.  8. -6. -1. -4.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1=np.random.randint(0,10,10)
x2=np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))

[0 2 4 6 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
#suicide mode on
defaults=np.seterr(all="ignore")
x=np.ones(1)/0
x1=np.seterr(**defaults)
#equivalently with context manager
with np.errstate(all="ignore"):
  np.arange(3)/0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
#they are not equal
#A=np.sqrt(-1)    # ans=1j
#B=np.emath.sqrt(-1)     # ans=nan
#A!=B
np.sqrt(-1)==np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday=np.datetime64("today")-np.timedelta64(1)
today=np.datetime64("today")
tomorrow=np.datetime64("today")+np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)


2022-08-17
2022-08-18
2022-08-19


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x=np.arange("2016-07","2016-08",dtype="datetime64[D]")
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A=np.ones(3)*1
B=np.ones(3)*2
np.add(A,B,out=A)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-3., -3., -3.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
X=np.random.uniform(0,10,10)

#5 diferent ways
print(X-X%1)
print(X//1)
print(np.floor(X))
print(X.astype(int))
print(np.trunc(X))

[1. 9. 9. 5. 1. 9. 0. 1. 2. 3.]
[1. 9. 9. 5. 1. 9. 0. 1. 2. 3.]
[1. 9. 9. 5. 1. 9. 0. 1. 2. 3.]
[1 9 9 5 1 9 0 1 2 3]
[1. 9. 9. 5. 1. 9. 0. 1. 2. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
X=np.tile(np.arange(0,5),(5,1))
print(X)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
X=np.zeros((5,5))
X+=np.arange(5)
print(X)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generator():
  for x in range(10):
    yield x
X=np.fromiter(generator(),dtype=float,count=-1)
print(X)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
X=np.linspace(0,1,11,endpoint=False)[1:]
print(X)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
X=np.random.random(10)
X.sort()
print(X)

[0.1439594  0.35081228 0.40405044 0.41421826 0.55262783 0.61928739
 0.66544879 0.79976388 0.83000516 0.98156763]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
X=np.arange(10)
np.add.reduce(X)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
X=np.random.randint(0,2,5)
Y=np.random.randint(0,2,5)
#comparison of value
equal=np.allclose(A,B)
print(equal)
#checking both the shape and the value ,no tolerance(value shuld be exactly equal)
equal=np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [3]:
X=np.zeros(10)
X.flags.writeable=False
X[0] = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
X=np.random.random((10,2))
m,n=X[:,0],X[:,1]
A=np.sqrt(m**2+n**2)
B=np.arctan2(n,m)
print(A)
print(B)


[0.947352   1.08916529 0.80683022 0.8560712  0.31212099 0.58981138
 1.09276997 0.82487602 0.64386131 0.8515923 ]
[0.97161137 1.08338581 0.19156387 1.35593126 0.408403   0.9288687
 0.65252491 1.04792993 0.35744765 1.24244207]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
X=np.random.random(10)
X[X.argmax()]=0
print(X)

[0.         0.15319625 0.34703366 0.70204951 0.78318957 0.20616058
 0.21821138 0.00565326 0.04576242 0.40215444]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
X=np.zeros((5,5),[("x",float),("y",float)])
X["x"],X["y"]=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(X)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X=np.arange(8)
Y=X+0.5
C=1.0/np.subtract.outer(X,Y)
print(np.linalg.det(C))


3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for x in [np.int8,np.int32,np.int64]:
  print(np.iinfo(x).min)
  print(np.iinfo(x).max)
for x in [np.float32,np.float64]:
  print(np.finfo(x).min)
  print(np.finfo(x).max)
  print(np.finfo(x).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
X=np.zeros((10,10))
print(X)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
Z=np.arange(100)
V=np.random.uniform(0,100)
index=(np.abs(Z-V)).argmin()
print(Z[index])

56


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z=np.zeros(10,[('postion',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
A=np.random.random((10,2))
M,N=np.atleast_2d(A[:,0],A[:,1])
B=np.sqrt((M-M.T)**2+(N-N.T)**2)
print(B)

[[0.         0.68576093 0.39458422 0.21446511 0.16804573 0.22933317
  0.32202947 0.70320278 0.21262847 0.45225394]
 [0.68576093 0.         1.0453418  0.88812182 0.60102487 0.66140245
  0.44585964 0.64077492 0.84647057 0.6277849 ]
 [0.39458422 1.0453418  0.         0.1849539  0.44514936 0.40315575
  0.71655714 0.83389473 0.19905961 0.58178572]
 [0.21446511 0.88812182 0.1849539  0.         0.30365562 0.29612166
  0.53463997 0.77980624 0.0899179  0.51644747]
 [0.16804573 0.60102487 0.44514936 0.30365562 0.         0.09370118
  0.35079432 0.53523126 0.24740188 0.28796792]
 [0.22933317 0.66140245 0.40315575 0.29612166 0.09370118 0.
  0.44411262 0.49265292 0.21923727 0.23153597]
 [0.32202947 0.44585964 0.71655714 0.53463997 0.35079432 0.44411262
  0.         0.75678788 0.53052146 0.57734592]
 [0.70320278 0.64077492 0.83389473 0.77980624 0.53523126 0.49265292
  0.75678788 0.         0.69343678 0.26348379]
 [0.21262847 0.84647057 0.19905961 0.0899179  0.24740188 0.21923727
  0.53052146 0.69343

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
A=(np.random.rand(10)*100).astype(np.float32)
B=A.view(np.int32)
B[:]=A
print(B)

[ 2 99 78 11 89 48 40 35 25 83]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
S=StringIO('''1,2,3,4,5
         6, , ,7,8,
         , , 9,10,11
''')
Z=np.genfromtxt(S,delimiter=",",dtype=np.int)
print(Z)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


ValueError: ignored

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
z=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(z):
    print(index,value)
for index,value in np.ndindex(z.shape):
    print(index,z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
0 [0 1 2]
0 [0 1 2]
0 [0 1 2]
1 [3 4 5]
1 [3 4 5]
1 [3 4 5]
2 [6 7 8]
2 [6 7 8]
2 [6 7 8]


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X,Y=np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D=np.sqrt(X*X+Y*Y)
sigma,mu=1.0,0.0
G=np.exp(-((D-mu)**2/(2.0*sigma**2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace=False),1)
print(Z)


[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X=np.random.rand(5,10)
Y=X-X.mean(axis=1,keepdims=True)
print(Y)

[[-0.18401593  0.33176255 -0.4501619  -0.56758529 -0.00589269  0.28972923
   0.28853815  0.24054287 -0.01945324  0.07653626]
 [ 0.33193626 -0.12184369 -0.34284621 -0.15097718  0.07483957 -0.11123499
   0.36838603  0.41845872 -0.42903939 -0.03767911]
 [-0.38711436  0.04415564 -0.2519325  -0.09829668 -0.08910474  0.21688286
   0.31254302  0.06408675 -0.00164779  0.1904278 ]
 [ 0.37637413  0.10875436 -0.38863759 -0.26816351  0.17731573 -0.04895601
   0.11978339 -0.12318476 -0.30934375  0.35605801]
 [-0.07270553  0.38831773 -0.2984267   0.40006437  0.08546065 -0.31668659
   0.31785491 -0.11394048 -0.30081237 -0.089126  ]]


In [ ]:
#older version
Y=X-X.mean(axis=1).reshape(-1,1)
print(Y)

[[-0.18401593  0.33176255 -0.4501619  -0.56758529 -0.00589269  0.28972923
   0.28853815  0.24054287 -0.01945324  0.07653626]
 [ 0.33193626 -0.12184369 -0.34284621 -0.15097718  0.07483957 -0.11123499
   0.36838603  0.41845872 -0.42903939 -0.03767911]
 [-0.38711436  0.04415564 -0.2519325  -0.09829668 -0.08910474  0.21688286
   0.31254302  0.06408675 -0.00164779  0.1904278 ]
 [ 0.37637413  0.10875436 -0.38863759 -0.26816351  0.17731573 -0.04895601
   0.11978339 -0.12318476 -0.30934375  0.35605801]
 [-0.07270553  0.38831773 -0.2984267   0.40006437  0.08546065 -0.31668659
   0.31785491 -0.11394048 -0.30081237 -0.089126  ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
X=np.random.randint(0,10,(3,3))
print(X)
print(X[X[:,1].argsort()])

[[8 2 7]
 [6 3 2]
 [1 9 8]]
[[8 2 7]
 [6 3 2]
 [1 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
X=np.random.randint(0,3,(3,10))
print((~X.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
X=np.random.uniform(0,1,10)
Y=0.5
M=X.flat[np.abs(X-Y).argmin()]
print(M)

0.4958943906744765


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A=np.arange(3).reshape(3,1)

B=np.arange(3).reshape(1,3)

iter=np.nditer([A,B,None])
for x,y,z in iter:z[...]=x+y
print(iter.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [5]:
class NameArray(np.ndarray):
  def__new__(cls,array,name="no name"):
    obj=np.asarray(array).view(cls)
    obj.name=name
    return obj
  def __array_finalize__(self,obj):
    if obj is None:return
    self.info=getattr(obj,"name","noname")
X=NameArray(np.arange(10),"range_10")
print(X.name)

SyntaxError: ignored

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
X=np.ones(10)
Y=np.random.randint(0,len(X),20)
X+=np.bincount(Y,minlength=len(X))
print(X)

[2. 4. 2. 2. 3. 2. 4. 7. 2. 2.]


In [ ]:
np.add.at(X,Y,1)
print(X)

[ 3.  7.  3.  3.  5.  3.  7. 13.  3.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X=[1,2,3,4,5,6]
Y=[1,3,9,3,4,1]
Z=np.bincount(X,Y)
print(Z)

[0. 1. 3. 9. 3. 4. 1.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w,h=256,256
A=np.random.randint(0,4,(h,w,3)).astype(np.ubyte)
colors=np.unique(A.reshape(-1,3),axis=0)
n=len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A=np.random.randint(0,10,(3,4,3,4))
sum=A.sum(axis=(-2,-1))
print(sum)
sum=A.reshape(A.shape[:2]+(-1,)).sum(axis=-1)
print(sum)

[[68 63 58 36]
 [56 47 59 50]
 [69 33 54 62]]
[[68 63 58 36]
 [56 47 59 50]
 [69 33 54 62]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
A=np.random.uniform(0,1,100)
B=np.random.randint(0,10,100)
A_sums=np.bincount(B,weights=A)
A_counts=np.bincount(B)
A_means=A_sums/A_counts
print(A_means)


[0.46128066 0.59326448 0.57891638 0.48081712 0.39575231 0.66400962
 0.42931921 0.43859843 0.31976035 0.36699848]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A=np.random.uniform(0,1,(5,5))
B=np.random.uniform(0,1,(5,5))
np.diag(np.dot(A,B))

array([1.4516199 , 1.19656052, 2.03029812, 0.53371588, 1.43077094])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
A=np.array([1,2,3,4,5])
n=3
A1=np.zeros(len(A)+(len(A)-1)*(n))
A1[::n+1]=A
print(A1)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A=np.ones((5,5,3))
B=2*np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A=np.arange(25).reshape(5,5)
A[[0,1]]=A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces=np.random.randint(0,100,(10,3))
F=np.roll(faces.repeat(2,axis=1),-1,axis=1)
F=F.reshape(len(F)*3,2)
F=np.sort(F,axis=1)
G=F.view(dtype=[('p0',F.dtype),('p1',F.dtype)])
G=np.unique(G)
print(G)

[( 0,  4) ( 0, 45) ( 4, 45) ( 5,  7) ( 5, 57) ( 6, 15) ( 6, 51) ( 7,  8)
 ( 7, 45) ( 7, 52) ( 7, 57) ( 7, 90) ( 8, 45) (12, 49) (12, 92) (13, 54)
 (13, 97) (15, 51) (17, 71) (17, 72) (18, 54) (18, 94) (41, 72) (41, 93)
 (49, 92) (52, 90) (54, 94) (54, 97) (71, 72) (72, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
A=np.bincount([1,1,2,3,4,4,6])
B=np.repeat(np.arange(len(A)),A)
print(A)

[0 2 1 1 2 0 1]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a,n=3):
  ret=np.cumsum(a,dtype=float)
  ret[n:]=ret[n:]-ret[:-n]
  return ret[n-1:]/n
Z=np.arange(20)
print(moving_average(Z,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks
def rolling(a,window):
  shape=(a.size-window+1,window)
  strides=(a.strides[0],a.strides[0])
  return stride_tricks.as_strided(a,shape=shape,strides=strides)
Z=rolling(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z=np.random.randint(0,2,100)
np.logical_not(Z,out=Z)
z=np.random.uniform(-1.0,1.0,100)
np.negative(Z,out=Z)

array([-1,  0,  0,  0,  0,  0, -1,  0,  0,  0, -1,  0, -1,  0, -1, -1,  0,
       -1,  0, -1, -1, -1,  0, -1, -1,  0,  0, -1,  0, -1, -1, -1, -1,  0,
        0,  0, -1,  0, -1, -1, -1, -1, -1,  0, -1, -1,  0, -1,  0,  0, -1,
       -1, -1,  0,  0, -1,  0, -1, -1, -1, -1,  0, -1, -1, -1, -1,  0, -1,
       -1,  0,  0,  0,  0, -1,  0, -1, -1, -1,  0, -1, -1, -1,  0, -1, -1,
       -1,  0, -1,  0,  0, -1,  0, -1,  0,  0, -1,  0, -1, -1, -1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0,P1,p):
  T=P1-P0
  L=(T**2).sum(axis=1)
  U=-((P0[:,0]-p[...,0])*T[:,0]+(P0[:,1]-p[...,1])*T[:,1])/L 
  U=U.reshape(len(U),1)
  D=P0+U*T-p
  return np.sqrt((D**2).sum(axis=1))
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(1,2))
print(distance(P0,P1,p))

[ 1.72729799 15.00754888 13.23697094 11.07990762  3.68698096  4.18777574
  1.04810374  0.93189024  2.30045043  8.53387535]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0=np.random.uniform(-10,10,(10,2))
P1=np.random.uniform(-10,10,(10,2))
p=np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[7.84778810e+00 4.93852616e+00 7.96579464e+00 1.11614241e+01
  4.00756460e+00 1.30024079e+01 3.80139917e+00 1.01718297e+01
  1.33327895e+01 1.18999370e+00]
 [1.33827119e+01 4.75203577e+00 2.76049367e+00 4.82998643e+00
  7.31930662e+00 5.61074170e-01 6.02312758e+00 1.23082811e+00
  5.13350936e+00 1.28543112e+01]
 [8.67257264e-01 1.57473424e+01 1.20540656e+01 3.71300994e-01
  7.20644062e+00 1.39657751e+01 6.43927765e+00 2.46811576e+00
  2.01452498e+01 1.43632733e+00]
 [1.18779785e+01 3.84592073e-01 6.47047227e+00 1.67922125e+01
  2.98019630e+00 1.31320401e+01 8.74529373e+00 1.45265913e+01
  1.03707158e+01 1.91850410e+00]
 [6.78896029e+00 5.65980231e+00 9.18309751e+00 1.10190947e+01
  5.22011170e+00 1.41679798e+01 2.93676943e+00 1.06802338e+01
  1.45037266e+01 1.51323543e-02]
 [8.73606506e+00 7.66087675e+00 2.89383292e+00 4.71169889e+00
  1.64109366e+00 6.13046100e+00 2.39316450e+00 1.62609229e+00
  1.04208711e+01 7.18174154e+00]
 [1.08360136e+01 5.88877452e+00 8.95452936e-01 5.66839650e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
from textwrap import fill
Z=np.random.randint(0,10,(10,10))
shape=(5,5)
fill=0
position=(1,1)
R=np.ones(shape,dtype=Z.dtype)*fill
P=np.array(list(position)).astype(int)
Rs=np.array(list(R.shape)).astype(int)
Zs=np.array(list(Z.shape)).astype(int)

R_start=np.zeros(len(shape),).astype(int)
R_stop=np.array(list(shape)).astype(int)
Z_start=(P-Rs//2)
Z_stop=(P+Rs//2)+Rs%2

R_start=(R_start-np.minimum(Z_start,0)).tolist()
Z_start=(np.maximum(Z_start,0)).tolist()
R_stop=np.maximum(R_start,(R_stop-np.maximum(Z_stop-Zs,0))).tolist()
Z_stop=(np.minimum(Z_stop,Zs)).tolist()

r=[slice(start,stop) for start,stop in zip(R_start,R_stop)]
z=[slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r]=Z[z]
print(Z)
print(R)

[[5 7 1 1 0 3 4 9 8 0]
 [7 6 7 2 9 9 8 7 4 6]
 [6 4 3 7 3 0 7 3 8 5]
 [7 7 8 1 2 9 5 2 3 1]
 [1 1 0 8 3 3 3 3 7 0]
 [2 9 5 9 4 8 9 7 7 1]
 [5 7 6 8 4 8 8 1 9 1]
 [1 7 6 4 2 9 0 4 4 5]
 [3 1 6 2 6 5 0 5 7 5]
 [2 5 3 8 8 4 2 0 5 8]]
[[0 0 0 0 0]
 [0 5 7 1 1]
 [0 7 6 7 2]
 [0 6 4 3 7]
 [0 7 7 8 1]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z=np.arange(1,15,dtype=np.uint32)
R=stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z=np.random.uniform(0,1,(10,10))
U,S,V=np.linalg.svd(Z)
rank=np.sum(S>1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z=np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

4


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z=np.random.randint(0,5,(10,10))
n=3
i=1+(Z.shape[0]-3)
j=1+(Z.shape[1]-3)
C=stride_tricks.as_strided(Z,shape=(i,j,n,n),strides=Z.strides+Z.strides)
print(C)


[[[[0 4 1]
   [3 1 1]
   [1 3 3]]

  [[4 1 1]
   [1 1 3]
   [3 3 1]]

  [[1 1 4]
   [1 3 2]
   [3 1 4]]

  [[1 4 2]
   [3 2 3]
   [1 4 2]]

  [[4 2 0]
   [2 3 3]
   [4 2 3]]

  [[2 0 0]
   [3 3 3]
   [2 3 1]]

  [[0 0 4]
   [3 3 4]
   [3 1 4]]

  [[0 4 0]
   [3 4 4]
   [1 4 3]]]


 [[[3 1 1]
   [1 3 3]
   [1 3 1]]

  [[1 1 3]
   [3 3 1]
   [3 1 3]]

  [[1 3 2]
   [3 1 4]
   [1 3 0]]

  [[3 2 3]
   [1 4 2]
   [3 0 4]]

  [[2 3 3]
   [4 2 3]
   [0 4 3]]

  [[3 3 3]
   [2 3 1]
   [4 3 4]]

  [[3 3 4]
   [3 1 4]
   [3 4 2]]

  [[3 4 4]
   [1 4 3]
   [4 2 1]]]


 [[[1 3 3]
   [1 3 1]
   [1 1 3]]

  [[3 3 1]
   [3 1 3]
   [1 3 2]]

  [[3 1 4]
   [1 3 0]
   [3 2 3]]

  [[1 4 2]
   [3 0 4]
   [2 3 0]]

  [[4 2 3]
   [0 4 3]
   [3 0 2]]

  [[2 3 1]
   [4 3 4]
   [0 2 2]]

  [[3 1 4]
   [3 4 2]
   [2 2 0]]

  [[1 4 3]
   [4 2 1]
   [2 0 1]]]


 [[[1 3 1]
   [1 1 3]
   [2 1 2]]

  [[3 1 3]
   [1 3 2]
   [1 2 0]]

  [[1 3 0]
   [3 2 3]
   [2 0 3]]

  [[3 0 4]
   [2 3 0]
   [0 3 2]]

  [[0 4 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
  def __setitem__(self,index,value):
    i,j=index
    super(Symetric,self).__setitem__((i,j),value)
    super(Symetric,self).__setitem__((j,i),value)
def symetric(Z):
  return np.asarray(Z+Z.T-np.diag(Z.diagonal())).view(Symetric)
S=symetric(np.random.randint(0,10,(5,5)))
S[2,3]=42
print(S)


[[ 9 12 10  4  9]
 [12  7 15 10 14]
 [10 15  0 42 17]
 [ 4 10 42  9 10]
 [ 9 14 17 10  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n=10,20
M=np.ones((p,n,n))
V=np.ones((p,n,1))
S=np.tensordot(M,V,axes=[[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z=np.ones((16,16))
k=4
S=np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis=0),np.arange(0,Z.shape[1],k),axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
  N=(Z[0:-2,0:-2]+Z[0:-2,1:-1] +Z[0:-2,2:]+
     Z[1:-1,0:-2]              +Z[1:-1,2:]+
     Z[2: ,0:-2] + Z[2:,1:-1]    +Z[2:,2:])
  birth=(N==3)&(Z[1:-1,1:-1]==0)
  survive=((N==2)|(N==3)) &(Z[1:-1,1:-1]==1)
  Z[...]=0
  Z[1:-1,1:-1][birth|survive]=1
  return Z
Z=np.random.randint(0,2,(50,50))
for i in range(100):Z=iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z=np.arange(10000)
np.random.shuffle(Z)
n=5
print(Z[np.argsort(Z)[-n:]])
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9999 9998 9997 9995 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:

def cartesian(arrays):
  arrays=[np.asarray(a) for a in arrays]
  shape=(len(x) for x in arrays)
  ix=np.indices(shape,dtype=int)
  ix=ix.reshape(len(arrays),-1).T
  for n,arr in enumerate(arrays):
    ix[:,n]=arrays[n][ix[:,n]]
  return ix
print(cartesian(([1,2,3],[4,5],[6,7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z=np.array([("hello",2.5,3),("world",3.6,2)])
R=np.core.records.fromarrays(Z.T,names="col1,col2,col3",formats="S8,f8,i8")
print(R)


[(b'hello', 2.5, 3) (b'world', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x=np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.91 s ± 235 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
157 ms ± 1.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
133 ms ± 2.12 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A=np.random.randint(0,5,(8,3))
B=np.random.randint(0,5,(2,2))
C=(A[...,np.newaxis,np.newaxis]==B)
rows=np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 3 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z=np.random.randint(0,5,(10,3))
print(Z)
E=np.all(Z[:,1:]==Z[:,:-1],axis=1)
U=Z[~E]
print(U)


[[0 1 4]
 [2 0 0]
 [2 4 3]
 [4 0 0]
 [4 4 4]
 [3 0 3]
 [0 1 0]
 [0 4 1]
 [4 0 4]
 [3 4 0]]
[[0 1 4]
 [2 0 0]
 [2 4 3]
 [4 0 0]
 [3 0 3]
 [0 1 0]
 [0 4 1]
 [4 0 4]
 [3 4 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I=np.array([0,1,2,3,15,16,32,64,128])
B=((I.reshape(-1,1)&(2**np.arange(8))) !=0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z=np.random.randint(0,2,(6,3))
T=np.ascontiguousarray(Z).view(np.dtype((np.void,Z.dtype.itemsize*Z.shape[1])))
_,idx=np.unique(T,return_index=True)
uZ=Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]


In [ ]:
uZ=np.unique(Z,axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A=np.random.uniform(0,1,10)
B=np.random.uniform(0,1,10)
np.einsum('i->',A)
np.einsum('i,i->i',A,B)
np.einsum('i,i',A,B)
np.einsum('i,j->ij',A,B)

array([[0.11826644, 0.41638836, 0.26601532, 0.08516437, 0.26791111,
        0.04156734, 0.17331118, 0.1652547 , 0.15293321, 0.31562017],
       [0.12451757, 0.43839712, 0.28007591, 0.08966584, 0.2820719 ,
        0.04376443, 0.18247178, 0.17398946, 0.1610167 , 0.33230269],
       [0.1765593 , 0.62162383, 0.39713276, 0.1271414 , 0.39996298,
        0.06205564, 0.25873529, 0.24670781, 0.22831313, 0.47118756],
       [0.1438807 , 0.50657016, 0.32362918, 0.10360935, 0.32593556,
        0.05057003, 0.21084709, 0.20104573, 0.18605564, 0.38397749],
       [0.02169485, 0.07638249, 0.04879798, 0.01562259, 0.04914575,
        0.00762513, 0.03179229, 0.0303144 , 0.02805414, 0.05789752],
       [0.01449581, 0.05103636, 0.03260526, 0.01043852, 0.03283763,
        0.00509487, 0.0212426 , 0.02025512, 0.01874489, 0.03868529],
       [0.15579702, 0.54852473, 0.35043242, 0.11219036, 0.35292981,
        0.05475828, 0.22830962, 0.2176965 , 0.20146492, 0.41577883],
       [0.13803688, 0.48599543, 0.3104847

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
X=np.arange(0,10*np.pi,0.1)
a=1
m=a*X*np.cos(X)
n=a*X*np.sin(X)
dr=(np.diff(m)**2+np.diff(n)**2)**.5
r=np.zeros_like(m)
r[1:]=np.cumsum(dr)
r_int=np.linspace(0,r.max(),200)
m_int=np.interp(r_int,r,m)
n_int=np.interp(r_int,r,n)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X=np.asarray([[1.0,0.0,3.0,8.0],[2.0,0.0,1.0,1.0],[1.5,2.5,1.0,0.0]])
n=4
M=np.logical_and.reduce(np.mod(X,1)==0,axis=-1)
M&=(X.sum(axis=-1)==n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X=np.random.randn(100)
N=1000
idx=np.random.randint(0,X.size,(N,X.size))
means=X[idx].mean(axis=1)
confint=np.percentile(means,[2.5,97.5])
print(confint)

[-0.39597819 -0.0128037 ]
